name: API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          # Removed cache option since no lock file is present

      - name: Install dependencies
        run: npm install

      - name: Run contract tests
        run: npm run test:contract

      - name: Run functional tests
        run: npm run test:functional

      - name: Generate report
        run: npm run report

      - name: Show report location
        run: echo "Report generated in reports directory"